#!/bin/bash

# Set the directory containing your Jekyll posts
POSTS_DIR="./_posts"

# Set the new last modified date (current date in YYYY-MM-DD format)
NEW_DATE=$(date +"%Y-%m-%d")

# Loop through each markdown file in the posts directory
for file in "$POSTS_DIR"/*.md; do
  echo "Updating file: $file"

  # Check if the file contains a 'last_modified_at' attribute
  if grep -q "last_modified_at:" "$file"; then
    # Update the existing last modified date
    sed -i "s/last_modified_at: .*/last_modified_at: $NEW_DATE/" "$file"
  else
    # Add the last modified date if it doesn't exist
    sed -i "/^---$/a last_modified_at: $NEW_DATE" "$file"
  fi

  echo "Updated last_modified_at date to $NEW_DATE in $file"
done

echo "All files have been updated."
